const CONFIG={email:'mfmfournier@yahoo.com',whatsapp:'34665687061',instagram:'https://www.instagram.com/mfournier1414/',excel:'obras.xlsx',bio:'bio.txt'};
const SERIES={BrokenFrame:{folder:'BrokenFrame',label:'BrokenFrame'},Habitats:{folder:'Habitats',label:'Habitats'},Balloons:{folder:'Balloons',label:'Balloons'},Other:{folder:'Other',label:'OtherWorks'}};
const noCache=()=>`v=${Date.now()}`;
function normalizeSerie(value){const raw=String(value||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,'');if(raw==='brokenframe'||raw==='brokenframes')return'BrokenFrame';if(raw==='habitats'||raw==='habitat')return'Habitats';if(raw==='balloons'||raw==='baloons'||raw==='baloon')return'Balloons';if(raw==='other'||raw==='otherworks'||raw==='otros')return'Other';return value}
function getValue(object,names){for(const name of names){if(object[name]!==undefined&&object[name]!==null&&String(object[name]).trim()!=='')return object[name]}return''}
function addText(parent,tag,className,text){if(!text)return;const element=document.createElement(tag);element.className=className;element.textContent=text;parent.appendChild(element)}
function buyerMessage(work){const title=work.titulo||work.imagen;return`Hola Manuel,\n\nEstoy interesado/a en esta obra:\n\nTítulo: ${title}\nSerie: ${work.serie}\nImagen: ${work.imagen}\nDimensiones: ${work.dimensiones}\nTécnica: ${work.tecnica}\nPrecio: ${work.precio}\n\n¿Podrías facilitarme más información?\n\nGracias.`}
function makeCard(work){const folder=SERIES[work.serie].folder;const title=work.titulo||work.imagen;const card=document.createElement('article');card.className='card';const media=document.createElement('div');media.className='work-media';const image=document.createElement('img');image.className='work-image';image.src=`${folder}/${encodeURI(work.imagen)}`;image.alt=title;image.loading='lazy';image.decoding='async';image.onerror=()=>{media.classList.add('image-error');media.textContent=`No se encuentra la imagen: ${work.imagen}`};media.appendChild(image);card.appendChild(media);const body=document.createElement('div');body.className='card-body';addText(body,'h3','',title);addText(body,'p','meta',work.dimensiones);addText(body,'p','meta',work.tecnica);addText(body,'p','price',work.precio);const actions=document.createElement('div');actions.className='acciones-compra';const message=encodeURIComponent(buyerMessage(work));const whatsapp=document.createElement('a');whatsapp.className='btn-whatsapp';whatsapp.href=`https://wa.me/${CONFIG.whatsapp}?text=${message}`;whatsapp.target='_blank';whatsapp.rel='noopener';whatsapp.textContent='WhatsApp';const email=document.createElement('a');email.className='btn-email';email.href=`mailto:${CONFIG.email}?subject=${encodeURIComponent(`Solicitud de compra - ${title}`)}&body=${message}`;email.textContent='Email / Correo';actions.append(whatsapp,email);body.appendChild(actions);card.appendChild(body);return card}
function updateArrows(shell){const gallery=shell.querySelector('.horizontal-gallery');const previous=shell.querySelector('.gallery-prev');const next=shell.querySelector('.gallery-next');const max=Math.max(0,gallery.scrollWidth-gallery.clientWidth);previous.disabled=gallery.scrollLeft<=2;next.disabled=gallery.scrollLeft>=max-2}
function setupGallery(shell){const gallery=shell.querySelector('.horizontal-gallery');const previous=shell.querySelector('.gallery-prev');const next=shell.querySelector('.gallery-next');const distance=()=>Math.max(gallery.clientWidth*.92,320);previous.addEventListener('click',()=>gallery.scrollBy({left:-distance(),behavior:'smooth'}));next.addEventListener('click',()=>gallery.scrollBy({left:distance(),behavior:'smooth'}));gallery.addEventListener('scroll',()=>updateArrows(shell),{passive:true});gallery.addEventListener('keydown',event=>{if(event.key==='ArrowLeft')gallery.scrollBy({left:-distance(),behavior:'smooth'});if(event.key==='ArrowRight')gallery.scrollBy({left:distance(),behavior:'smooth'})});window.addEventListener('resize',()=>updateArrows(shell));updateArrows(shell)}
function renderWorks(works){document.querySelectorAll('[data-series]').forEach(gallery=>{const series=gallery.dataset.series;gallery.replaceChildren();const selected=works.filter(work=>work.serie===series);if(!selected.length){const empty=document.createElement('div');empty.className='empty';empty.textContent=`No hay obras cargadas para ${SERIES[series].label}.`;gallery.appendChild(empty)}else selected.forEach(work=>gallery.appendChild(makeCard(work)));requestAnimationFrame(()=>updateArrows(gallery.closest('.gallery-shell')))})}
async function loadExcel(){const response=await fetch(`${CONFIG.excel}?${noCache()}`,{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);const workbook=XLSX.read(await response.arrayBuffer(),{type:'array'});const rows=XLSX.utils.sheet_to_json(workbook.Sheets[workbook.SheetNames[0]],{defval:''});return rows.map(row=>{const imagen=String(getValue(row,['Imagen','imagen','IMAGEN'])).trim();const serie=normalizeSerie(getValue(row,['Serie','serie','SERIE']));return{imagen,serie,titulo:String(getValue(row,['Titulo','Título','titulo','TITULO'])||imagen).trim(),dimensiones:String(getValue(row,['Dimensiones','dimensiones','DIMENSIONES'])||'').trim(),tecnica:String(getValue(row,['Tecnica','Técnica','tecnica','TECNICA'])||'').trim(),precio:String(getValue(row,['Precio','precio','PRECIO'])||'Consultar').trim()}}).filter(work=>work.imagen&&SERIES[work.serie])}
function renderBio(text){const content=document.getElementById('bioContent');const status=document.getElementById('bioStatus');const pre=document.createElement('pre');pre.className='bio-literal';pre.textContent=text.replace(/^\uFEFF/,'');content.replaceChildren(pre);status.hidden=true}
async function loadBio(){const status=document.getElementById('bioStatus');status.hidden=false;status.className='bio-status';status.textContent='Cargando biografía...';try{const response=await fetch(`${CONFIG.bio}?${noCache()}`,{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);renderBio(await response.text())}catch(error){console.error(error);status.className='bio-status bio-error';status.textContent='No se ha podido cargar bio.txt. Comprueba que está junto a index.html.'}}
function setupBio(){const link=document.getElementById('bioNavLink');const section=document.getElementById('bio');link.addEventListener('click',async event=>{event.preventDefault();section.hidden=false;await loadBio();section.scrollIntoView({behavior:'smooth',block:'start'})})}
async function init(){document.getElementById('year').textContent=new Date().getFullYear();document.getElementById('emailLink').href=`mailto:${CONFIG.email}`;document.getElementById('instagramLink').href=CONFIG.instagram;document.querySelectorAll('.gallery-shell').forEach(setupGallery);setupBio();try{renderWorks(await loadExcel())}catch(error){console.error(error);document.querySelectorAll('[data-series]').forEach(gallery=>{const empty=document.createElement('div');empty.className='empty';empty.textContent='No se ha podido cargar obras.xlsx. Comprueba que está junto a index.html.';gallery.replaceChildren(empty)})}}
document.addEventListener('DOMContentLoaded',init);
